### 404 =>ok
GET http://localhost:5000/trucquiexistepas

### / =>ok
GET http://localhost:5000/


##########################
# détail par utilisateur #
##########################

### détail par utilisateur avec son article + commentaire =>ok
GET http://localhost:5000/user/3/article/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDM4NjUyMywiZXhwIjoxNjM0Mzg4MzIzfQ.u0Wa5aasQCVDkezXvhHwfjkEvwEoqG6co11v2IkrUkc


### détail par un autre utilisateur avec article + commentaire =>ok
GET http://localhost:5000/user/2/article/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDM4NjUyMywiZXhwIjoxNjM0Mzg4MzIzfQ.u0Wa5aasQCVDkezXvhHwfjkEvwEoqG6co11v2IkrUkc

### les articles de l'utilisateur => ok
GET http://localhost:5000/user/3/articles

### les commentaire de l'utilisateur => ok
GET http://localhost:5000/user/3/comments

### les revenus de l'utilisateur => ok
GET http://localhost:5000/user/3/infosimulations
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDM4NjUyMywiZXhwIjoxNjM0Mzg4MzIzfQ.u0Wa5aasQCVDkezXvhHwfjkEvwEoqG6co11v2IkrUkc


### un revenu de l'utilisateur => ok
GET http://localhost:5000/user/3/income/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoiY2lkYWFoMjIiLCJlbWFpbCI6InJlZ2lzQGFhaC5jb20iLCJyb2xlIjoxLCJpYXQiOjE2MzM4Nzc1NzcsImV4cCI6MTYzMzg3OTM3N30.27Kgm0G1M0sULCiZ0zMV5O76kca5a47QFOTJov0Zo14

### Le revenu d'un autre utilisateur Message errreur =>ok
GET http://localhost:5000/user/1/income/2

###### creer un revenues => ok
post http://localhost:5000/user/3/income
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDEzOTgxNCwiZXhwIjoxNjM0MTQxNjE0fQ.TOPYME4Qh3_lTXRBeG7WACsFGFI5SlBjLwNUqFWm2h

{
  "year": 2001,
  "situation": "couple",
  "nb_child": 5,
  "age": 40,
  "disability_rate": 0.8,
  "place_of_residence": true,
  "apl": true,
   "applicant_income_without_activity": 0,
    "applicant_income_with_activity": 0,
    "spouses_income": 19000,
    "child_income1": 0,
    "child_income2":0,
    "child_income3": 0,
    "child_income4": 0,
    "child_income5" : 0
}

###### Supprime un revenues => ok
DELETE  http://localhost:5000/user/3/income/9

### mise a jour un revenu => ok
PATCH http://localhost:5000/user/3/income/9
Content-Type: application/json

{
  "year": 1999,
  "amount": 90000012,
  "situation": "couple",
  "nb_child": 0
}



################
# Les Articles #
################


###Liste un article => ok
GET http://localhost:5000/article/1

### Lister les articles de l'utilisateur avec commentaire => ok
GET http://localhost:5000/user/3/articles
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInBzZXVkbyI6InBvc3RtYW4zIiwiZW1haWwiOiIkMmIkMTAkYmJ1ekp0Yk9Fbm12WENyb1VKTzVzT3RLSS5PMEZPaHA4TUxSNFdpNXR2WmNEYXZyUnlhVlMiLCJyb2xlIjoxLCJpYXQiOjE2MzI2NTUyNDAsImV4cCI6MTYzMjY1NzA0MH0.cp9vJPq9bzsOBwYYBpysozjzL7mDx0zNFa8KGL2A2jw

### Liste un article de l'utilisateur + ses commentaire => OK
GET http://localhost:5000/user/3/article/15
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDA2MDM5NCwiZXhwIjoxNjM0MDYyMTk0fQ.6lZyslXimbjjNOW63sW5RwG1NqLdrN7P8ClzjIaT3wU



####################
# les commentaires #
####################




###### Lister tous les commentaire d'un utilisateur=> OK
GET http://localhost:5001/user/3/comments

###### Liste un commentaire  et l'article=> ok
GET http://localhost:5000/user/3/comment/3

###### creer un commentaire => ok
post http://localhost:5000/user/3/article/2/comment
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDA2MDM5NCwiZXhwIjoxNjM0MDYyMTk0fQ.6lZyslXimbjjNOW63sW5RwG1NqLdrN7P8ClzjIaT3wU

{
  "content": "Mon commentaire que je poste"
}

### Suprimer un commentaire => ok
DELETE http://localhost:5000/user/3/comment/18

### mise a jour un commentaire => ok
PATCH http://localhost:5000/user/3/comment/14
Content-Type: application/json

{
  "content": " ",
  "user_id": 3,
  "article_id": 2
}



#################
# Les Comptages #
#################



### Compte tous les revenues => ok
GET http://localhost:5000/incomesCount



### Compte tous les articles => ok
GET http://localhost:5000/articlesCount

### Compte tous les articles => a faire plutard
GET http://localhost:5000/Count
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDA1NzI4NSwiZXhwIjoxNjM0MDU5MDg1fQ.5mVQ6d_lA-l_Gt_80NnKGdc3dir4zi8Iam2E8fNo9sc











# détail par utilisateur
### détaile par article =>ok

GET http://localhost:5000/user/3/articles
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDA1NzI4NSwiZXhwIjoxNjM0MDU5MDg1fQ.5mVQ6d_lA-l_Gt_80NnKGdc3dir4zi8Iam2E8fNo9sc


### login
POST http://localhost:5000/login
Content-Type: application/json

{
  "pseudo": "cidaah22",
  "password": "cide"
}

###
GET http://localhost:5000/refreshToken
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDA1NzI4NSwiZXhwIjoxNjM0MDU5MDg1fQ.5mVQ6d_lA-l_Gt_80NnKGdc3dir4zi8Iam2E8fNo9sc

###
GET http://localhost:5000/user/10
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDA1NzI4NSwiZXhwIjoxNjM0MDU5MDg1fQ.5mVQ6d_lA-l_Gt_80NnKGdc3dir4zi8Iam2E8fNo9sc




### login
POST http://localhost:5000/login
Content-Type: application/json

{
  "pseudo": "cidaahAdmin",
  "password": "cidaah"
}


### Créer un utilisateur => ok
POST http://localhost:5000/signup
Content-Type: application/json

{
  "pseudo": "cidaahAdmin",
  "password": "cidaah",
  "email": "regis@aah.com",
  "birthdate": "11-05-1895",
  "role": 3,
  "disability_rate": 0.8,
  "place_of_residence": true,
  "apl": true
}





### Créer une simulation => ok
POST http://localhost:5000/simulation
Content-Type: application/json

{
   
}


### Lister les articles de l'utilisateur avec commentaire => ok
GET http://localhost:5000/user/3/guestbooks
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDM4Nzk1NCwiZXhwIjoxNjM0Mzg5NzU0fQ.zhzhG_USbhabG7-CeGZ_13JoH1M_U-w6c7PPokATvQw




### 
POST http://localhost:5000/simulation
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDM4Nzk1NCwiZXhwIjoxNjM0Mzg5NzU0fQ.zhzhG_USbhabG7-CeGZ_13JoH1M_U-w6c7PPokATvQw

{
 "content": "j'ai fait une simulation",
}


### je compte le nombre total de simulation
GET http://localhost:5000/countnbsimulations


### je compte et montre toutes les simulations
GET http://localhost:5000/simulations
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDA1NzI4NSwiZXhwIjoxNjM0MDU5MDg1fQ.5mVQ6d_lA-l_Gt_80NnKGdc3dir4zi8Iam2E8fNo9sc





###
GET http://localhost:5000/user/10/simulations
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwicHNldWRvIjoiY2lkYWFoMiIsImVtYWlsIjoicmVnaXNAYWFoLmNvbSIsInJvbGUiOjMsImlhdCI6MTYzNDM4Nzk1NCwiZXhwIjoxNjM0Mzg5NzU0fQ.zhzhG_USbhabG7-CeGZ_13JoH1M_U-w6c7PPokATvQw